#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path
from urllib.parse import quote_plus


def terraform_output(terraform_dir: Path) -> dict[str, object]:
    result = subprocess.run(
        ["terraform", "output", "-json"],
        cwd=str(terraform_dir),
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)


def get_output_value(outputs: dict[str, object], key: str) -> str:
    value_obj = outputs.get(key)
    if not isinstance(value_obj, dict):
        raise RuntimeError(f"Missing terraform output: {key}")
    value = value_obj.get("value")
    if value is None:
        raise RuntimeError(f"Terraform output {key} is empty")
    if not isinstance(value, (str, int, bool)):
        raise RuntimeError(f"Terraform output {key} has unsupported type")
    return str(value)


def build_database_url(
    *,
    username: str,
    password: str,
    endpoint: str,
    port: str,
    db_name: str,
) -> str:
    encoded_password = quote_plus(password)
    return (
        f"postgresql+asyncpg://{username}:{encoded_password}@{endpoint}:{port}/{db_name}"
    )


def write_local_env_file(path: Path, database_url: str) -> None:
    lines: list[str] = []
    if path.is_file():
        replaced = False
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith("DATABASE_URL="):
                lines.append(f"DATABASE_URL={database_url}")
                replaced = True
            else:
                lines.append(line)
        if not replaced:
            if lines and lines[-1].strip():
                lines.append("")
            lines.append(f"DATABASE_URL={database_url}")
    else:
        lines = [
            "# Generated by infra/scripts/set_database_url_from_rds.py",
            "# API uses SSL automatically for non-localhost RDS hosts.",
            f"DATABASE_URL={database_url}",
            "",
        ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build DATABASE_URL from RDS terraform outputs and upload to SSM."
    )
    parser.add_argument(
        "--terraform-dir",
        default="infra/terraform",
        help="Path to Terraform directory (default: infra/terraform)",
    )
    parser.add_argument("--region", default="ap-south-1")
    parser.add_argument(
        "--profile",
        default=os.getenv("AWS_PROFILE"),
        help="AWS CLI profile (or set AWS_PROFILE).",
    )
    parser.add_argument("--project", default="relaydesk")
    parser.add_argument("--environment", default="prod")
    parser.add_argument(
        "--password",
        default=os.getenv("RDS_DB_PASSWORD", ""),
        help="RDS master password (or set RDS_DB_PASSWORD env var).",
    )
    parser.add_argument(
        "--write-local-env",
        default="",
        help="Also write DATABASE_URL to this file (e.g. api/.env.local).",
    )
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if not args.password:
        print("Provide --password or set RDS_DB_PASSWORD.", file=sys.stderr)
        return 1

    terraform_dir = Path(args.terraform_dir).resolve()
    outputs = terraform_output(terraform_dir)
    endpoint = get_output_value(outputs, "rds_endpoint")
    db_name = get_output_value(outputs, "rds_database_name")
    username = get_output_value(outputs, "rds_master_username")
    port = get_output_value(outputs, "rds_port")
    public_flag = get_output_value(outputs, "rds_publicly_accessible").lower()

    database_url = build_database_url(
        username=username,
        password=args.password,
        endpoint=endpoint,
        port=port,
        db_name=db_name,
    )
    ssm_name = f"/{args.project}/{args.environment}/api/DATABASE_URL"

    if args.dry_run:
        print(f"[dry-run] would set {ssm_name}")
        print(database_url)
        if args.write_local_env:
            print(f"[dry-run] would write {args.write_local_env}")
        if public_flag != "true":
            print(
                "note: rds_publicly_accessible is false — use infra/scripts/rds_tunnel.ps1 "
                "or enable public access in terraform.tfvars",
                file=sys.stderr,
            )
        return 0

    if args.write_local_env:
        local_path = Path(args.write_local_env).resolve()
        write_local_env_file(local_path, database_url)
        print(f"wrote {local_path}")

    cmd = [
        "aws",
        "ssm",
        "put-parameter",
        "--name",
        ssm_name,
        "--value",
        database_url,
        "--type",
        "SecureString",
        "--overwrite",
        "--region",
        args.region,
    ]
    if args.profile:
        cmd.extend(["--profile", args.profile])

    subprocess.run(cmd, check=True)
    print(f"set {ssm_name}")
    if public_flag == "true":
        print(
            f"RDS is public — connect locally with host {endpoint}, port {port}, SSL required."
        )
    else:
        print(
            "RDS is private — direct laptop access will fail unless you run rds_tunnel.ps1 "
            "or set rds_publicly_accessible = true in terraform.tfvars."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
