#!/usr/bin/env python3
"""Write api/.env.local DATABASE_URL for local dev via SSM RDS tunnel (localhost:15432)."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path
from urllib.parse import quote_plus


def terraform_output(terraform_dir: Path) -> dict[str, object]:
    result = subprocess.run(
        ["terraform", "output", "-json"],
        cwd=str(terraform_dir),
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)


def get_output_value(outputs: dict[str, object], key: str) -> str:
    value_obj = outputs.get(key)
    if not isinstance(value_obj, dict):
        raise RuntimeError(f"Missing terraform output: {key}")
    value = value_obj.get("value")
    if not value:
        raise RuntimeError(f"Terraform output {key} is empty")
    if not isinstance(value, (str, int)):
        raise RuntimeError(f"Terraform output {key} has unsupported type")
    return str(value)


def write_database_url(path: Path, database_url: str) -> None:
    lines: list[str] = []
    if path.is_file():
        replaced = False
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith("DATABASE_URL="):
                lines.append(f"DATABASE_URL={database_url}")
                replaced = True
            else:
                lines.append(line)
        if not replaced:
            if lines and lines[-1].strip():
                lines.append("")
            lines.append(f"DATABASE_URL={database_url}")
    else:
        lines = [
            "# Generated by infra/scripts/write_local_tunnel_database_url.py",
            "# Start infra/scripts/rds_tunnel.ps1 before running the API.",
            f"DATABASE_URL={database_url}",
            "",
        ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Write DATABASE_URL for local API dev through the RDS SSM tunnel."
    )
    parser.add_argument(
        "--terraform-dir",
        default="infra/terraform",
        help="Path to Terraform directory (default: infra/terraform)",
    )
    parser.add_argument(
        "--env-file",
        default="api/.env.local",
        help="Env file to update (default: api/.env.local)",
    )
    parser.add_argument(
        "--local-port",
        type=int,
        default=15432,
        help="Local tunnel port (default: 15432, matches rds_tunnel.ps1)",
    )
    parser.add_argument(
        "--password",
        default=os.getenv("RDS_DB_PASSWORD", ""),
        help="RDS master password (or set RDS_DB_PASSWORD env var).",
    )
    args = parser.parse_args()

    if not args.password:
        print("Provide --password or set RDS_DB_PASSWORD.", file=sys.stderr)
        return 1

    outputs = terraform_output(Path(args.terraform_dir).resolve())
    username = get_output_value(outputs, "rds_master_username")
    db_name = get_output_value(outputs, "rds_database_name")

    encoded_password = quote_plus(args.password)
    database_url = (
        f"postgresql+asyncpg://{username}:{encoded_password}"
        f"@127.0.0.1:{args.local_port}/{db_name}"
    )

    env_path = Path(args.env_file).resolve()
    write_database_url(env_path, database_url)
    print(f"wrote {env_path}")
    print("Start the tunnel in another terminal: .\\infra\\scripts\\rds_tunnel.ps1")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
